### ISSUE TITLE
Add Error printing + checks so that a single error won't break the thread

### ISSUE THREAD

**Issue by ap73567** [OrnitOnGithub/lan-chatroom#7]
**Error printing:**

line 97 in main.py:
```
    except Exception as e:
        print(e)
```

**Error found:**
Exception in thread Thread-1 (listen):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/etudiant/Downloads/lan-chatroom/main.py", line 44, in listen
    net.listen()
  File "/Users/etudiant/Downloads/lan-chatroom/network.py", line 102, in listen
    with zipfile.ZipFile(folder_zip, 'r') as archive:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by OrnitOnGithub** [comment]
I'll add the error printing. The error seems to be some weird artefact caused by a badly intercepted package. When I redo the networking this issue should appear less and/or not be problematic.
